name: Test Federation

on:
  workflow_dispatch:

env:
  orch-project: "dataform2looker-demo"
  dataform-repo: "https://github.com/yangliudevoteam/copy_alex.git"

jobs:
  CICD :
    name: CICD checks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dataform2Looker 
        run: |
          pip install git+https://github.com/devoteamgcloud/dataform2looker.git --force-reinstall
  
      - name: Install Dataform CLI
        run:
          npm i -g @dataform/cli@^3.0.0-beta

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: '${{env.orch-project}}'
          workload_identity_provider: 'projects/509432560350/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          audience: audience-default
      
      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v2'

      # - name: test table existence
      #   run: |
      #     gcloud auth list
      #     bq show data__datamart.airport_metrics


        
      - name: Clone dataform2looker-demo and compile dataform json file
        run: |
          git clone ${{env.dataform-repo}} demo-project
          cd demo-project
          dataform install
          dataform compile --json > output.json

      - name: Run dataform2looker taking output.json as input
        run: |
         ls
         echo "here"
         cd demo-project
         ls
         mkdir -p views
         df2looker --source-file-path output.json --target-dir views

      - name: Compare folders
        run: |
         ls
          # Define folder paths
          FOLDER1="views"
          FOLDER2="demo-project/views"

          echo "Comparing $FOLDER1 with $FOLDER2..."

          # Run diff command
          diff -r "$FOLDER1" "$FOLDER2" || true

          # If differences are found, output to a file
          DIFF_OUTPUT="differences.txt"
          diff -r "$FOLDER1" "$FOLDER2" > "$DIFF_OUTPUT" || true

          # Check if the differences file exists and print its content
          if [ -s "$DIFF_OUTPUT" ]; then
            echo "Differences found:"
            cat "$DIFF_OUTPUT"
          else
            echo "No differences found."
          fi



          
