name: Test Federation

on:
  workflow_dispatch:

env:
  orch-project: "dataform2looker-demo"
  dataform-repo: "https://github.com/AKyrloglou-Devoteam/dataform2looker-demo.git"

jobs:
  CICD :
    name: CICD checks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dataform2Looker 
        run: |
          pip install git+https://github.com/devoteamgcloud/dataform2looker.git --force-reinstall
  

      - name: Install Dataform CLI
        run:
          npm i -g @dataform/cli@^3.0.0-beta
        # working-directory: examples/dataform2looker-demo-main

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: '${{env.orch-project}}'
          workload_identity_provider: 'projects/509432560350/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          audience: audience-default
      
      - name: Clone dataform2looker-demo
        run: |
          git clone https://github.com/AKyrloglou-Devoteam/dataform2looker-demo.git demo-project
          cd demo-project
          poetry install

      - name: Compile and Test
        run: |
          cd demo-project
          df2looker --source-file-path ./dataform-compile.json --target-dir ./views --verbose
          ls ./views
