name: Test Federation

on:
  workflow_dispatch:

env:
  orch-project: "dataform2looker-demo"
  dataform-repo: "https://github.com/yangliudevoteam/copy_alex.git"

jobs:
  CICD :
    name: CICD checks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dataform2Looker 
        run: |
          pip install git+https://github.com/devoteamgcloud/dataform2looker.git --force-reinstall
  

      - name: Install Dataform CLI
        run:
          npm i -g @dataform/cli@^3.0.0-beta
        # working-directory: examples/dataform2looker-demo-main

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: '${{env.orch-project}}'
          workload_identity_provider: 'projects/509432560350/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          audience: audience-default

      - name: Locate and Copy Credential File
        run: |
          CREDENTIAL_FILE=$(ls $GITHUB_WORKSPACE | grep -E '.*\.json$')
          if [ -z "$CREDENTIAL_FILE" ]; then
            echo "Error: Credential file not found"
            exit 1
          fi
          echo "Credential file found: $CREDENTIAL_FILE"
          cp "$GITHUB_WORKSPACE/$CREDENTIAL_FILE" demo-project/
        
      - name: Clone dataform2looker-demo and compile dataform json file
        run: |
          git clone ${{env.dataform-repo}} demo-project
          cd demo-project
          dataform install
          dataform compile --json > output.json
    
      - name: Run dataform2looker taking output.json as input
        run: |
         cd demo-project
         ls
         df2looker --source-file-path output.json --target-dir views



          
